[supervisord]
nodaemon=true
user=root
logfile=/tmp/log/supervisord.log
pidfile=/tmp/run/supervisord.pid

[program:dbus]
command=bash -c "rm -f /run/dbus/pid /run/dbus/system_bus_socket && exec dbus-daemon --system --nofork"
priority=10
autorestart=true

[program:guacd]
command=guacd -b 127.0.0.1 -l 4822 -f
priority=20
autorestart=true

[program:xrdp-sesman]
command=xrdp-sesman --nodaemon
priority=30
autorestart=true

[program:xrdp]
command=xrdp --nodaemon
priority=40
autorestart=true

[program:tomcat]
command=/usr/local/tomcat/bin/catalina.sh run
environment=GUACAMOLE_HOME="/etc/guacamole",LD_LIBRARY_PATH="/usr/local/apr/lib",CATALINA_OPTS="-Xms512m -Xmx1024m -server -XX:+TieredCompilation -Dorg.apache.tomcat.websocket.DEFAULT_BUFFER_SIZE=8192"
priority=50
autorestart=true

[program:openvscode]
command=/usr/local/code-server/bin/code-server --bind-addr 0.0.0.0:3000 --auth none --disable-telemetry --disable-update-check --disable-workspace-trust
user=$USER_NAME
environment=HOME="/home/$USER_NAME",USER="$USER_NAME",DISPLAY=":10.0",XDG_RUNTIME_DIR="/run/user/$USER_UID"
priority=60
autorestart=true
